#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Filename: utils/generate_manifest.py
Version: 1.0.0 (Kwetal)
Role: Integrity Tool
Objective: Automatically rebuild the FILE_MANIFEST.md by parsing file headers across all core phases.
"""

import os
import re
from pathlib import Path

def get_header_info(file_path):
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
            objective = re.search(r'Objective:\s*(.*)', content)
            role = re.search(r'Role:\s*(.*)', content)
            if objective:
                return objective.group(1).strip()
            elif role:
                return role.group(1).strip()
    except Exception:
        pass
    return "No objective defined."

def generate():
    project_root = Path(__file__).parent.parent
    
    print("# Seestar Organizer: Automated File Manifest (v1.0 Kwetal)\n")
    print("*This manifest is auto-generated by parsing file headers. Do not edit manually.*\n")
    
    phases = {
        "🛫 PREFLIGHT (Daytime)": project_root / "core/preflight",
        "🚀 FLIGHT (Nighttime)": project_root / "core/flight",
        "🛬 POSTFLIGHT (Processing)": project_root / "core/postflight"
    }

    for phase_name, path in phases.items():
        print(f"## {phase_name}")
        if path.exists():
            for script in sorted(path.glob("*.py")):
                if script.name == "__init__.py": continue
                info = get_header_info(script)
                relative_path = script.relative_to(project_root)
                print(f"* `{relative_path}`: {info}")
        else:
            print("* *Phase directory not yet initialized.*")
        print()

    print("## 🛠️ UTILS & ROOT")
    for script in sorted((project_root / "utils").glob("*.py")):
        info = get_header_info(script)
        print(f"* `utils/{script.name}`: {info}")

if __name__ == "__main__":
    generate()
