"""
Filename: utils/generate_manifest.py
Objective: Automatically rebuild the FILE_MANIFEST.md by parsing 'Objective:' tags.
"""
import os

def extract_objective(filepath):
    """Gathers the text following the 'Objective:' tag in a file."""
    try:
        with open(filepath, 'r') as f:
            content = f.read()
            # Look for Objective: and grab the text until the end of the line or docstring
            if "Objective:" in content:
                parts = content.split("Objective:")[1].split('\n')[0]
                return parts.strip().replace('"""', '').replace('#', '').strip()
    except Exception:
        return "No objective defined."
    return "No objective defined."

def build_manifest():
    print("# Seestar Organizer: Automated File Manifest (v1.0 Kwetal)")
    print("\n*This manifest is auto-generated by parsing file headers. Do not edit manually.*")
    
    # Define the directories to scan in order of importance
    scan_dirs = ['core', 'logic', 'utils', 'scripts', 'tests']
    
    for folder in scan_dirs:
        if not os.path.exists(folder):
            continue
            
        print(f"\n## 📂 {folder.capitalize()}")
        files = sorted([f for f in os.listdir(folder) if f.endswith('.py') or f.endswith('.service')])
        
        for f in files:
            path = os.path.join(folder, f)
            objective = extract_objective(path)
            print(f"* `{path}`: {objective}")

    # Check root directory for main entry points
    print(f"\n## 🚀 Root Entry Points")
    root_files = sorted([f for f in os.listdir('.') if f.endswith('.py') or f.endswith('.service')])
    for f in root_files:
        objective = extract_objective(f)
        print(f"* `{f}`: {objective}")

if __name__ == "__main__":
    build_manifest()
