#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Seestar Organizer - Manifest Generator
# Path: ~/seestar_organizer/utils/generate_manifest.py
# Purpose: Scrapes file headers to rebuild FILE_MANIFEST.md automatically.
# ----------------------------------------------------------------

import os

ROOT_DIR = os.path.expanduser("~/seestar_organizer")
MANIFEST_PATH = os.path.join(ROOT_DIR, "FILE_MANIFEST.md")

def get_header_info(filepath):
    purpose = "No objective defined."
    try:
        with open(filepath, 'r', errors='ignore') as f:
            for line in f:
                if "Purpose:" in line or "Objective:" in line:
                    purpose = line.split(":", 1)[1].strip()
                    break
    except:
        pass
    return purpose

def generate():
    sections = {
        "🛫 PREFLIGHT (Daytime)": "core/preflight",
        "🚀 FLIGHT (Nighttime)": "core/flight",
        "🧪 POSTFLIGHT (Processing)": "core/postflight",
        "🛠️ UTILS & ROOT": ["core/utils", "utils", "core"]
    }

    with open(MANIFEST_PATH, 'w') as m:
        m.write("# Seestar Organizer: Automated File Manifest\n\n")
        m.write("*This manifest is auto-generated by parsing file headers.*\n\n")

        for title, folder in sections.items():
            m.write(f"## {title}\n")
            folders = [folder] if isinstance(folder, str) else folder
            
            for fld in folders:
                target = os.path.join(ROOT_DIR, fld)
                if not os.path.exists(target): continue
                
                # List files in this specific folder (not recursive to avoid clutter)
                for file in sorted(os.listdir(target)):
                    if file.endswith(".py"):
                        purpose = get_header_info(os.path.join(target, file))
                        m.write(f"* `{fld}/{file}`: {purpose}\n")
            m.write("\n")

if __name__ == "__main__":
    generate()
    print("✅ FILE_MANIFEST.md has been rebuilt.")
